package pecl3;

import java.util.ArrayList;
import javax.swing.JTextField;

/**
 *
 * @author Álvaro Zamorano
 * @author Gabriel López
 */
public class VentanaCliente extends javax.swing.JFrame {

    //Atributos de la clase
    private final ArrayList<JTextField> surtidoresjt;
    private final ArrayList<JTextField> operariosjt;

    /**
     * Constructor de la clase
     */
    public VentanaCliente() {
        initComponents();

        surtidoresjt = new ArrayList<>(8);
        operariosjt = new ArrayList<>(8);

        surtidoresjt.add(0, Surtidor1);
        surtidoresjt.add(1, Surtidor2);
        surtidoresjt.add(2, Surtidor3);
        surtidoresjt.add(3, Surtidor4);
        surtidoresjt.add(4, Surtidor5);
        surtidoresjt.add(5, Surtidor6);
        surtidoresjt.add(6, Surtidor7);
        surtidoresjt.add(7, Surtidor8);

        operariosjt.add(0, Operario1);
        operariosjt.add(1, Operario2);
        operariosjt.add(2, Operario3);
        operariosjt.add(3, Operario4);
        operariosjt.add(4, Operario5);
        operariosjt.add(5, Operario6);
        operariosjt.add(6, Operario7);
        operariosjt.add(7, Operario8);

        RecibirDatos rd = new RecibirDatos(jTextField1, surtidoresjt, operariosjt, this);
        rd.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        Surtidor1 = new javax.swing.JTextField();
        Surtidor2 = new javax.swing.JTextField();
        Surtidor3 = new javax.swing.JTextField();
        Surtidor4 = new javax.swing.JTextField();
        Surtidor5 = new javax.swing.JTextField();
        Surtidor6 = new javax.swing.JTextField();
        Surtidor7 = new javax.swing.JTextField();
        Surtidor8 = new javax.swing.JTextField();
        Operario1 = new javax.swing.JTextField();
        Operario2 = new javax.swing.JTextField();
        Operario3 = new javax.swing.JTextField();
        Operario4 = new javax.swing.JTextField();
        Operario5 = new javax.swing.JTextField();
        Operario7 = new javax.swing.JTextField();
        Operario6 = new javax.swing.JTextField();
        Operario8 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PECL3 - CLIENTE");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(750, 375));
        setResizable(false);
        getContentPane().setLayout(null);

        jTextField1.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(18, 40, 710, 30);

        Surtidor1.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        getContentPane().add(Surtidor1);
        Surtidor1.setBounds(20, 140, 120, 30);

        Surtidor2.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        getContentPane().add(Surtidor2);
        Surtidor2.setBounds(220, 140, 121, 30);

        Surtidor3.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        getContentPane().add(Surtidor3);
        Surtidor3.setBounds(420, 140, 120, 30);

        Surtidor4.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        getContentPane().add(Surtidor4);
        Surtidor4.setBounds(610, 140, 120, 30);

        Surtidor5.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        getContentPane().add(Surtidor5);
        Surtidor5.setBounds(20, 270, 118, 30);

        Surtidor6.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        getContentPane().add(Surtidor6);
        Surtidor6.setBounds(220, 270, 121, 30);

        Surtidor7.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        getContentPane().add(Surtidor7);
        Surtidor7.setBounds(420, 270, 120, 30);

        Surtidor8.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        getContentPane().add(Surtidor8);
        Surtidor8.setBounds(610, 270, 120, 30);

        Operario1.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        getContentPane().add(Operario1);
        Operario1.setBounds(20, 170, 120, 30);

        Operario2.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        getContentPane().add(Operario2);
        Operario2.setBounds(220, 170, 120, 30);

        Operario3.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        getContentPane().add(Operario3);
        Operario3.setBounds(420, 170, 120, 30);

        Operario4.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        getContentPane().add(Operario4);
        Operario4.setBounds(610, 170, 120, 30);

        Operario5.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        getContentPane().add(Operario5);
        Operario5.setBounds(20, 300, 118, 30);

        Operario7.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        getContentPane().add(Operario7);
        Operario7.setBounds(420, 300, 120, 30);

        Operario6.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        getContentPane().add(Operario6);
        Operario6.setBounds(220, 300, 121, 30);

        Operario8.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        getContentPane().add(Operario8);
        Operario8.setBounds(610, 300, 120, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        jLabel20.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel20.setText("Surtidor 8");
        jPanel2.add(jLabel20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(600, 220, 140, 120);

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));

        jLabel13.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel13.setText("Surtidor 1");
        jPanel3.add(jLabel13);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 90, 140, 120);

        jPanel4.setBackground(new java.awt.Color(255, 255, 102));

        jLabel14.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel14.setText("Surtidor 2");
        jPanel4.add(jLabel14);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(210, 90, 140, 120);

        jPanel5.setBackground(new java.awt.Color(255, 255, 102));

        jLabel15.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel15.setText("Surtidor 3");
        jPanel5.add(jLabel15);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(410, 90, 140, 120);

        jPanel6.setBackground(new java.awt.Color(255, 255, 102));

        jLabel16.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel16.setText("Surtidor 4");
        jPanel6.add(jLabel16);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(600, 90, 140, 120);

        jPanel7.setBackground(new java.awt.Color(255, 255, 102));

        jLabel17.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel17.setText("Surtidor 5");
        jPanel7.add(jLabel17);

        getContentPane().add(jPanel7);
        jPanel7.setBounds(10, 220, 140, 120);

        jPanel8.setBackground(new java.awt.Color(255, 255, 102));

        jLabel18.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel18.setText("Surtidor 6");
        jPanel8.add(jLabel18);

        getContentPane().add(jPanel8);
        jPanel8.setBounds(210, 220, 140, 120);

        jPanel9.setBackground(new java.awt.Color(255, 255, 102));

        jLabel19.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel19.setText("Surtidor 7");
        jPanel9.add(jLabel19);

        getContentPane().add(jPanel9);
        jPanel9.setBounds(410, 220, 140, 120);

        jPanel1.setBackground(new java.awt.Color(153, 255, 102));

        jLabel21.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel21.setText("VEHÍCULOS ESPERANDO PARA ENTRAR EN LA GASOLINERA");
        jPanel1.add(jLabel21);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 730, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pecl3/gas-station.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 750, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VentanaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Operario1;
    private javax.swing.JTextField Operario2;
    private javax.swing.JTextField Operario3;
    private javax.swing.JTextField Operario4;
    private javax.swing.JTextField Operario5;
    private javax.swing.JTextField Operario6;
    private javax.swing.JTextField Operario7;
    private javax.swing.JTextField Operario8;
    private javax.swing.JTextField Surtidor1;
    private javax.swing.JTextField Surtidor2;
    private javax.swing.JTextField Surtidor3;
    private javax.swing.JTextField Surtidor4;
    private javax.swing.JTextField Surtidor5;
    private javax.swing.JTextField Surtidor6;
    private javax.swing.JTextField Surtidor7;
    private javax.swing.JTextField Surtidor8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
